---
title: Ziggy `R` script   
fontsize: 10
geometry: margin=1in
documentclass: article
linkcolor: blue
urlcolor: blue
citecolor: red
output:
  pdf_document:
    includes:
      in_header: # add .tex file with header content
    highlight: tango
    template: null
    toc: no
    toc_depth: 4
    number_sections: false
    fig_width: 4
    fig_height: 5
    fig_caption: true
    df_print: tibble 
    citation_package: biblatex # natbib
    latex_engine: xelatex #pdflatex # lualatex
    keep_tex: true # keep .tex file in dir 
  html_document:
    highlight: tango
    code_folding: hide
    toc: yes
    toc_depth: 4
    number_sections: no
    toc_float: yes
  word_document:
    highlight: tango
    keep_md: yes
    pandoc_args: --smart
    #reference: mystyles.docx
    toc: yes
inludes:
  before_body: before_body.tex
subtitle: 
tags:
- nothing
- nothingness
params: 
  date: !r Sys.Date()
  session: !r sessionInfo()  
  version: !r getRversion()
  email: "matthew.malishev@gmail.com"
  doi: https://github.com/darwinanddavis/UsefulCode
classoption: portrait
# ^['https://github.com/darwinanddavis/UsefulCode'] # footnote
vignette: >
  %\VignetteIndexEntry{Useful R code}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "all"} } });
</script>

```{r echo = FALSE}
# library(rmarkdown)
# setwd("")
# f <- list.files()[1]
# render(f, output_format='pdf_document')
```

```{r, set-options, echo = FALSE, cache = FALSE}
options(width=100)
knitr::opts_chunk$set(
 eval = TRUE, # run all code
 # echo = FALSE, # show code chunks in output 
 comment = "",
 tidy.opts=list(width.cutoff=100), # set width of code chunks in output
 tidy=TRUE, # make output as tidy
 message = FALSE,  # mask all messages
 warning = FALSE, # mask all warnings 
 size="small" # set code chunk size
)

# https://github.com/ucb-stat133/stat133-fall-2016/blob/master/hws/hw02-tables-ggplot.Rmd
knitr::opts_knit$set(root.dir=paste0(params$dir,"/")) # set working dir

# setwd(paste0(params$dir,"/")) # for running just in R not knitr
```

```{r,echo=F}
params$session
```

\  

## Packages used    
```{r,echo=F,eval=T}
packages <- c("evaluate","animation","RColorBrewer","dplyr","ggmap","RgoogleMaps","sp","maptools","scales","rgdal","ggplot2","leaflet","jsonlite","readr","devtools","mapdata","ggsn","mapview","mapproj","ggthemes","reshape2","grid")
list(packages)
```

\newpage  

## Script  
```{r,eval=F, echo=T}
# read in data ------------------------------------------------------------
countries <- c("Colombia","Ecuador","Peru","Panama")
# read in kml data from my google maps (drive route)
zp <- sf::st_read("ziggy.kml")
secondary_paths <- sf::st_read("secondary_paths.kml")
# get city coords
city_df <- c()
for(ll in 2:length(zp$Name)){
  city <- unlist(subset(zp,Name==as.character(zp$Name[ll]))$geometry)
  city <- city[2:1] # remove stupid zero
  city_df <- rbind(city_df,city)
  city_df <- city_df %>% data.frame()
}
colnames(city_df) <- c("lat","lon")
# high res map
d <- map_data("worldHires", countries)
# get latlon (uses api key) 
location <- c("Medellin","Bogotá")
city_secondary <- geocode(location, 
                          output = "latlon", 
                          source="google"
                          ) 
city_secondary <- city_secondary %>% data.frame()
# plot --------------------------------------------------------------------
dput(par(no.readonly=TRUE)) # reset graphical params
par()
# colour palettes 
bg <- "#f2f0ee" 
fg <- "#10163c" 
path_col <- "#f4d29f" 
border_col <- "c7d2f5" 
city_size <- 5
path_size <- 0.7
# plot 
ggplot() + # initiate plot dev
  geom_polygon(data=d,aes(x=long, y=lat, group = group), 
               fill = fg, col=border_col,size=0.1) + # add map polygon
  geom_sf(data=zp,color=path_col,size=path_size) + # add ziggy path
  geom_point(data=city_df,aes(lon,lat),
             col=path_col,size=city_size) + # add cities
  geom_point(data=city_secondary,aes(lon,lat),shape=21,
             fill=path_col,color=path_col,size=city_size) + # add secondary cities
  coord_sf(xlim=c(-75,-81),ylim=c(-2,8)) + # zoom window  
  theme_nothing() + # set minimal theme 
  theme( # panels
    panel.grid.major = element_line(colour = bg),
    panel.ontop = F, # to toggle panel grid visibility
    plot.background = element_rect(fill = bg)) 
# save to dir
ggsave(paste0("ziggy_",bg,"_",fg,"_",path_col,".pdf")
       , width = 9, height = 15, dpi = "retina", limitsize = F)
```

